From alpine:3.15

# GFW？ Comment out the following comments 
# {{
# COPY pip /root/.pip
# COPY luarocks /root/.luarocks
# }}

COPY nvim /nvim
ENV PATH = "/usr/local/go/bin:/root/.go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/root/.cargo/bin:${PATH}"
ENV GOPATH = "/usr/local/go"

# GFW? Comment out the following comments 
# {{
# RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
# }}
RUN apk add --update \
  git \
  alpine-sdk build-base\
  libtool \
  automake \
  m4 \
  npm \
  wget \
  autoconf \
  linux-headers \
  unzip \
  ncurses ncurses-dev ncurses-libs ncurses-terminfo \
  python3 \
  python3-dev \
  py3-pip \
  openssh-client \
  clang \
  nodejs \
  nodejs-dev \
  nodejs-doc \
  #go \
  fzf \
  nodejs \
  xz \
  curl \
  make \
  cmake \
  libintl \
  libtermkey \
  libvterm \
  #icu-data-full \
  unibilium \
  sqlite-dev \
  coreutils \
  zsh \
  #tree-sitter-cli \
  neovim && \
  pip3 install --user neovim pep8 black isort beautysh && \
  npm install -g @fsouza/prettierd && \
  npm install -g eslint_d && \
  npm install -g write-good && \
  npm install -g neovim && \
  npm install -g markdownlint --save-dev && \
  wget -O /tmp/go.tar.gz https://go.dev/dl/go1.18.9.linux-amd64.tar.gz && tar -xzvf /tmp/go.tar.gz -C /usr/local/ && \
	chmod a+x /usr/local/go/bin/go && ln -s /usr/local/go/bin/go /usr/local/bin/go
  # enable lazygit
  go install github.com/jesseduffield/lazygit@latest && \
  go install mvdan.cc/sh/v3/cmd/shfmt@latest && \
  mkdir /root/.config && \
  ln -s /nvim /root/.config/nvim && \
  curl https://sh.rustup.rs -sSf | sh -s -- -y && \
  source "$HOME/.cargo/env" && \
  cargo install stylua && \
  cargo install cbfmt && \
  cargo install tree-sitter-cli && \
  #nvim +PackerSync && \
  rm -rf /var/cache/apk/*

RUN nvim --headless +GoInstallBinaries +qa
RUN nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync' -c 'sleep 60' -c 'qa'

#https://www.sqlite.org/2022/sqlite-dll-win64-x64-3400100.zip
#cp sqlite3.dll /root/.config/sqlite3.dll
